### PR TITLE
Allow wildcards in rule_files

### PR DESCRIPTION
**Pull request by AMeng**
Allow an entire directory of rule files to be included. An example configuration would look like:

``` yaml

---
datadog:
  api_key: YOUR_API_KEY
  app_key: YOUR_APP_KEY

rule_directory: my_rules
```

### CODE REVIEW

**Comment by thesamet** [comment]
Thanks for working on this. I would prefer that instead of rule_directory, we would support wildcard in `rule_files`, for example:

```
rule_files:
- somedir/*.yml
```

Advantages: less cases in the config, some people write yml, others write yaml so I wouldn't want to hardcode a specific extension. In the future, we might do recursive search with **...

If you can switch the implementation to use python's glob through rule_files, I'd be happy to merge it in.

**Comment by AMeng** [comment]
@thesamet updated to allow wildcards in path names instead of using `rule_directory`.
I also fixed a couple of misnamed variables.

**Comment by AMeng** [comment]
@thesamet any chance you can take another look at this?

**Comment by thesamet** [comment]
Thank you for working on this. I squashed the two commits and merged.

**Pull request closed without merging**
